### ISSUE TITLE
咨询一下QNAP的ContainerStation可以进行配置么？

### ISSUE THREAD

**Issue by V1046-R** [pcrbot/HoshinoBot-Docker#1]
这方面的小白，不知道需要什么指令可以进行配置。

希望可以得到答复，感谢。

**Comment by yuudi** [comment]
不知道这个架构是什么，如果是 64位 amd 就可以，要是 arm 的话就得自己构建一下

**Comment by V1046-R** [comment]
> 不知道这个架构是什么，如果是 64位 amd 就可以，要是 arm 的话就得自己构建一下

感谢！我继续研究一下。
